language: "en-US"
early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - "develop"
      - "main"
      - "master"
  path_filters:
    - "!docs/**"
    - "!assets/**"
    - "!src/**/assets/**"
    - "!src/**/images/**"
    - "!**/__snapshots__/**"
    - "!**/*.snap"
    - "!**/*.map"
    - "!**/*.{png,jpg,jpeg,gif,svg,webp,ico,woff,woff2}"
    - "!**/package-lock.json"
    - "!**/yarn.lock"
    - "!**/pnpm-lock.yaml"
chat:
  auto_reply: true
